### ISSUE TITLE
does not compile with xapian 1.3.1

### ISSUE THREAD

**Issue by zeule** [zaufi/kate-cpp-helper-plugin#11]
Can not compile sources from git master for quite some time using Xapian 1.3.1. Compilation yields in many errors like the following:

/usr/include/xapian-1.3/xapian/types.h:25:3: error: #error "Never use <xapian/types.h> directly; include <xapian.h> instead."
 # error "Never use <xapian/types.h> directly; include <xapian.h> instead."

and there are  similar ones for various Xapian include files.
